# Uncomment the next line to define a global platform for your project
# platform :ios, '11.4'

target 'GameOfVerbs1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GameOfVerbs1
	 pod 'CSVImporter', '~> 1.7'
	 pod 'IQKeyboardManagerSwift'
     pod 'SVProgressHUD'
     pod 'Google-Mobile-Ads-SDK'

end
